# Generated by Django 4.1.7 on 2023-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_usertotpdetails_key_alter_usertotpdetails_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is2faActivated',
            field=models.BooleanField(default=False),
        ),
    ]
