# Generated by Django 4.1.7 on 2023-04-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userprofile_is2faactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Platform Name')),
            ],
            options={
                'db_table': 'Platform',
            },
        ),
        migrations.AlterField(
            model_name='usertotpdetails',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='Time delay'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platform',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.platform'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertotpdetails',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.platform'),
        ),
    ]
