# Generated by Django 4.1.7 on 2023-04-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_platform_alter_usertotpdetails_delay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='platform',
        ),
    ]
