# Generated by Django 4.1.7 on 2023-04-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_userprofile_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='platform',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.platform'),
            preserve_default=False,
        ),
    ]
