# Generated by Django 4.1.7 on 2023-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_userprofile_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotpdetails',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is_active'),
        ),
    ]
